### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Sanju",
  "email": "sanju@gmail.com",
  "address": "palayakaran, Chennai",
  "dateOfBirth": "2001-01-30",
  "registeredDate":"2025-12-11"
}

###